#!/usr/bin/env bash
# Bash that installs NGINX on server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
